import {StyleSheet} from 'react-native';
import {
  fontSizes,
  iconSizes,
  marginSizes,
  paddingSizes,
  screenWidth,
  sizes,
} from '../../theme/sizes';
import {colors} from '../../theme/colors';
import {moderateScale} from 'react-native-size-matters';

export const styles = StyleSheet.create({
  mainContainer: {
    backgroundColor: colors.black,
  },
  videoCon: {
    marginBottom: marginSizes.lg,
    borderBottomLeftRadius: 60,
    borderBottomRightRadius: 60,
    backgroundColor: colors.white,
    overflow: 'hidden',
  },
  video: {width: '100%', height: '100%', overflow: 'hidden'},
  mirrorCon: {
    top: 0,
    position: 'absolute',
    alignSelf: 'center',
    alignItems: 'center',
  },
  handle: {
    height: sizes.ssm,
    width: sizes.md,
    backgroundColor: colors.black,
  },
  mirror: {
    width: moderateScale(120),
    height: moderateScale(28),
    borderWidth: 2,
    borderRadius: 8,
  },
  buttonCon: {
    position: 'absolute',
    bottom: 50,
    left: moderateScale(50),
    flexDirection: 'row',
    width: '25%',
    justifyContent: 'space-between',
  },
  steeringContainer: {
    position: 'absolute',
    right: 50,
    bottom: -50,
  },
  steering: {
    width: iconSizes.steeringIcon,
    height: iconSizes.steeringIcon,
  },
  box: {
    width: 100,
    height: 100,
    backgroundColor: 'red',
  },

  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  imageContainer: {
    width: 200,
    height: 200,
  },
  image: {
    width: '100%',
    height: '100%',
    resizeMode: 'contain',
  },
  tooltipCommon: {
    position: 'absolute',
    backgroundColor: colors.tooltipBackground,
    padding: paddingSizes.md,
    borderRadius: 25,
  },

  tooltipOne: {
    width: '50%',
    justifyContent: 'center',
    alignSelf: 'center',
    top: moderateScale(50),
  },
  tooltipTwo: {
    width: '40%',
    justifyContent: 'center',
    alignSelf: 'center',
    top: moderateScale(50),
  },
  tooltipThree: {
    width: '33%',
    right: 10,
    top: moderateScale(75),
  },
  tooltipFour: {
    width: '33%',
    left: 20,
    top: moderateScale(40),
  },
  tooltipFive: {
    width: '33%',
    justifyContent: 'center',
    alignSelf: 'center',
    top: moderateScale(65),
  },
  tooltipText: {
    color: colors.whiteTextColor,
    fontSize: fontSizes.md,
    lineHeight: moderateScale(21.5),
  },
  nextButton: {
    color: colors.whiteTextColor,
    textDecorationLine: 'underline',
    fontSize: fontSizes.md,
    alignSelf: 'flex-end',
    marginTop: marginSizes.sm,
  },
  skipButton: {
    flexDirection: 'row',
    position: 'absolute',
    alignItems: 'center',
    right: 20,
    top: 20,
  },
  skipText: {
    color: colors.black,
    fontSize: fontSizes.md,
  },
  bottomNotch: {
    position: 'absolute',
    width: 0,
    height: 0,
    bottom: -20,
    alignSelf: 'center',
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 15,
    borderRightWidth: 15,
    borderBottomWidth: 20,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: colors.tooltipBackground,
    transform: [{rotate: '180deg'}],
  },
  topNotch: {
    position: 'absolute',
    width: 0,
    height: 0,
    top: -20,
    alignSelf: 'center',
    backgroundColor: 'transparent',
    borderStyle: 'solid',
    borderLeftWidth: 15,
    borderRightWidth: 15,
    borderBottomWidth: 20,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    borderBottomColor: colors.tooltipBackground,
  },
  instructionCon: {
    // height: moderateScale(50),
    // width: moderateScale(45),
    borderTopEndRadius: 50,
    borderBottomEndRadius: 50,
    backgroundColor: colors.instructionBackgroundColor,
    position: 'absolute',
    top: 50,
    borderColor: colors.white,
    borderTopWidth: 1,
    borderRightWidth: 1,
    borderBottomWidth: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  instructionExpButton: {
    width: '100%',
    height: '100%',
    flex: 1,
    marginStart: -4,
    paddingVertical: 8,
  },
  instructionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  instructor: {
    fontSize: moderateScale(0),
    color: colors.whiteTextColor,
    marginStart: 10,
    textDecorationStyle: 'solid',
  },
  instructionText: {
    fontSize: moderateScale(20),
    color: colors.whiteTextColor,
    fontWeight: 'bold',
  },
});
